# TF Syntax Basics

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.3.0


In [3]:
hello = tf.constant("Hello ")

In [5]:
world = tf.constant("World")

In [6]:
# tensor object
# a tensor is a fancy word for an n-dimensional array
type(hello)

tensorflow.python.framework.ops.Tensor

In [7]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [8]:
print(result)

b'Hello World'


In [9]:
a = tf.constant(10)
b = tf.constant(20)
type(a)

tensorflow.python.framework.ops.Tensor

In [11]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [12]:
print(result)

30


In [13]:
const = tf.constant(10)

In [14]:
fill_mat = tf.fill((4,4),10)

In [15]:
myzeros = tf.zeros((4,4))

In [16]:
myones = tf.ones((4,4))

In [17]:
myrandn = tf.random_normal((4,4), mean=0, stddev=1.0)

In [18]:
myrandu = tf.random_uniform((4,4), minval=0, maxval=1)

In [19]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [20]:
# Only really useful for jupyter notebook
sess = tf.InteractiveSession()

In [25]:
for op in my_ops:
    #print(sess.run(op))
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[ 0.60326791  2.94743848 -0.06379591 -0.1132656 ]
 [-1.79817116  0.27645758 -0.72134084 -1.05526936]
 [ 1.16572332 -0.01438756 -0.44823605  0.41527548]
 [ 1.33967829 -0.215763   -0.06231735 -0.25311425]]


[[ 0.79494989  0.50419688  0.78295279  0.39931953]
 [ 0.54748762  0.99466896  0.23166418  0.58403122]
 [ 0.7712512   0.84955549  0.13849306  0.09811652]
 [ 0.26560104  0.35879993  0.21266222  0.01175046]]




In [26]:
a = tf.constant([[1,2], [3,4]])

In [27]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [28]:
b = tf.constant([[10], [100]])

In [29]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [30]:
result = tf.matmul(a,b)

In [31]:
sess.run(result)

array([[210],
       [430]])